# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 876d9fe07a23495225cea01565b0867cd4ee173f11d45b37bc518a1e2c7657c2ef046f58fb579807905d8279c8c0a5881b42942b20c5f60e20757a8767506ded

test:
  secret_key_base: 78f472c61c62e809df3929fdf2ac4cec943a67565e3ff3e7a8608a9e1dd3a9bea14f02572bc1b179d117349a961bd694ff712d975bceaf0ae6e1f83fccff1e72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
